server:
  port: 8899
media:
  thread_num: 4
  rtmp_port: 7935
  rtsp_port: 7554
  http_port: 7080
  rtc_port: 8000
  rtc_host: 172.16.4.213
  auto_close: 0
  streamNoneReaderDelayMS: 30000
  maxStreamWaitMS: 1500
  enable_ts: 0
  enable_hls: 1
  enable_fmp4: 0
  enable_rtsp: 1
  enable_rtmp: 1
  enable_mp4: 0
  enable_hls_fmp4: 0
  enable_audio: 0
  mp4_as_player: 1
  mp4_max_second: 3600
  mp4_save_path: E:/media
  hls_save_path: E:/media
  rootPath: E:/media
  hls_demand: 0
  broadcastRecordTs: 1
  segDur: 3
  segNum: 3
  rtsp_demand: 0
  rtmp_demand: 0
  ts_demand: 1
  fmp4_demand: 1
  log_level: 2
  log_mask: 1  #1console 2file 4fun
  log_file_days: 1
  log_path: E:/media
